export type CalendarEvent = Readonly<{
  id: string;
  subject: string;
  start: string;
  end: string;
  timeZone?: string;
  location?: string;
  bodyPreview?: string;
  organizer?: string;
  attendees?: readonly string[];
}>;

export type CalendarListRequest = Readonly<{ startDateTime: string; endDateTime: string; limit?: number }>;
export type CalendarCreateRequest = Readonly<{ subject: string; start: string; end: string; timeZone?: string; location?: string; body?: string; attendees?: readonly string[] }>;
export type CalendarUpdateRequest = Readonly<{ id: string; subject?: string; start?: string; end?: string; timeZone?: string; location?: string; body?: string; attendees?: readonly string[] }>;

const GRAPH = "https://graph.microsoft.com/v1.0";
const TIMEOUT_MS = 15_000;
const MAX_LIMIT = 50;

function requiredToken(token?: string) { const value = token?.trim(); if (!value) throw new Error("MICROSOFT_GRAPH_ACCESS_TOKEN is not configured"); return value; }
function limit(value?: number) { const n = Number.isFinite(value) ? Math.floor(value as number) : 20; return Math.min(MAX_LIMIT, Math.max(1, n)); }
function requiredDate(value: string, name: string) { const v = value.trim(); if (!v || Number.isNaN(Date.parse(v))) throw new Error(`${name}_INVALID`); return v; }
function asAddress(value: unknown): string | undefined { if (!value || typeof value !== "object") return undefined; const address = "emailAddress" in value ? value.emailAddress : undefined; if (!address || typeof address !== "object") return undefined; const result = "address" in address ? address.address : undefined; return typeof result === "string" ? result : undefined; }
function asEvent(raw: unknown): CalendarEvent { if (!raw || typeof raw !== "object") throw new Error("CALENDAR_INVALID_RESPONSE"); const item = raw as Record<string, unknown>; const start = item.start && typeof item.start === "object" && "dateTime" in item.start ? item.start.dateTime : undefined; const end = item.end && typeof item.end === "object" && "dateTime" in item.end ? item.end.dateTime : undefined; const id = typeof item.id === "string" ? item.id : ""; const subject = typeof item.subject === "string" ? item.subject : ""; if (!id || !subject || typeof start !== "string" || typeof end !== "string") throw new Error("CALENDAR_INVALID_RESPONSE"); const attendees = Array.isArray(item.attendees) ? item.attendees.map(asAddress).filter((x): x is string => Boolean(x)) : []; const organizer = asAddress(item.organizer); const location = item.location && typeof item.location === "object" && "displayName" in item.location && typeof item.location.displayName === "string" ? item.location.displayName : undefined; const body = item.bodyPreview; return { id, subject, start, end, timeZone: item.start && typeof item.start === "object" && "timeZone" in item.start && typeof item.start.timeZone === "string" ? item.start.timeZone : undefined, location, bodyPreview: typeof body === "string" ? body : undefined, organizer, attendees }; }

export class MicrosoftGraphCalendarProvider {
  readonly name = "microsoft-graph-calendar";
  constructor(private readonly accessToken = process.env.MICROSOFT_GRAPH_ACCESS_TOKEN) {}
  private async request<T>(path: string, init?: RequestInit): Promise<T> { const token = requiredToken(this.accessToken); let response: Response; try { response = await fetch(`${GRAPH}${path}`, { ...init, headers: { accept: "application/json", authorization: `Bearer ${token}`, ...(init?.headers ?? {}) }, signal: AbortSignal.timeout(TIMEOUT_MS) }); } catch (error) { if (error instanceof DOMException && error.name === "TimeoutError") throw new Error("CALENDAR_PROVIDER_TIMEOUT"); throw error; } if (!response.ok) { if (response.status === 401 || response.status === 403) throw new Error("CALENDAR_PROVIDER_UNAUTHORIZED"); throw new Error(`CALENDAR_PROVIDER_HTTP_${response.status}`); } if (response.status === 204) return undefined as T; const contentType = response.headers.get("content-type") ?? ""; if (!contentType.toLowerCase().includes("application/json")) throw new Error("CALENDAR_PROVIDER_INVALID_CONTENT_TYPE"); return response.json() as Promise<T>; }
  async list(request: CalendarListRequest): Promise<readonly CalendarEvent[]> { const start = requiredDate(request.startDateTime, "CALENDAR_START"); const end = requiredDate(request.endDateTime, "CALENDAR_END"); if (Date.parse(end) <= Date.parse(start)) throw new Error("CALENDAR_RANGE_INVALID"); const params = new URLSearchParams({ startDateTime: start, endDateTime: end, "$top": String(limit(request.limit)), "$select": "id,subject,start,end,location,bodyPreview,organizer,attendees" }); const data = await this.request<{ value?: unknown[] }>(`/me/calendarView?${params.toString()}`, { headers: { Prefer: 'outlook.timezone="UTC"' } }); return (data.value ?? []).map(asEvent); }
  async read(id: string): Promise<CalendarEvent> { const value = id.trim(); if (!value) throw new Error("CALENDAR_ID_REQUIRED"); return asEvent(await this.request<unknown>(`/me/events/${encodeURIComponent(value)}?$select=id,subject,start,end,location,bodyPreview,organizer,attendees`)); }
  async create(request: CalendarCreateRequest): Promise<CalendarEvent> { const subject = request.subject.trim(); if (!subject) throw new Error("CALENDAR_SUBJECT_REQUIRED"); const start = requiredDate(request.start, "CALENDAR_START"); const end = requiredDate(request.end, "CALENDAR_END"); if (Date.parse(end) <= Date.parse(start)) throw new Error("CALENDAR_RANGE_INVALID"); return asEvent(await this.request<unknown>("/me/events", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ subject, start: { dateTime: start, timeZone: request.timeZone ?? "UTC" }, end: { dateTime: end, timeZone: request.timeZone ?? "UTC" }, ...(request.location?.trim() ? { location: { displayName: request.location.trim() } } : {}), ...(request.body?.trim() ? { body: { contentType: "Text", content: request.body.trim() } } : {}), ...(request.attendees?.length ? { attendees: request.attendees.map((address) => ({ emailAddress: { address: address.trim() }, type: "required" })) } : {}) }) })); }
  async update(request: CalendarUpdateRequest): Promise<CalendarEvent> { const id = request.id.trim(); if (!id) throw new Error("CALENDAR_ID_REQUIRED"); const payload: Record<string, unknown> = {}; if (request.subject !== undefined) { const subject = request.subject.trim(); if (!subject) throw new Error("CALENDAR_SUBJECT_REQUIRED"); payload.subject = subject; } if (request.start !== undefined) payload.start = { dateTime: requiredDate(request.start, "CALENDAR_START"), timeZone: request.timeZone ?? "UTC" }; if (request.end !== undefined) payload.end = { dateTime: requiredDate(request.end, "CALENDAR_END"), timeZone: request.timeZone ?? "UTC" }; if (request.location !== undefined) payload.location = { displayName: request.location.trim() }; if (request.body !== undefined) payload.body = { contentType: "Text", content: request.body }; if (request.attendees !== undefined) payload.attendees = request.attendees.map((address) => ({ emailAddress: { address: address.trim() }, type: "required" })); return asEvent(await this.request<unknown>(`/me/events/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) })); }
  async delete(id: string): Promise<{ id: string; deleted: boolean }> { const value = id.trim(); if (!value) throw new Error("CALENDAR_ID_REQUIRED"); await this.request<void>(`/me/events/${encodeURIComponent(value)}`, { method: "DELETE" }); return { id: value, deleted: true }; }
}
